version: '3.9'
services:
  user-service:
    container_name: dreamup-user-service
    image: dreamup-user-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.local
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - SQS_ENDPOINT=http://q_sqs-localstack_main:4566
    volumes:
      # There's a bunch of keys in the fixtures folder that we need to use
      - type: bind
        source: ./test/fixtures
        target: /app/test/fixtures
        read_only: true
      
      # We need to mount the public key for cognito local dev pool
      - type: bind
        source: ./cognito-local.pub
        target: /app/./cognito-local.pub
        read_only: true