name: Run Tests

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - README.md
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start DynamoDB
        run: docker compose -f dependencies.yml up -d

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Stop DynamoDB
        run: docker compose -f dependencies.yml down